package db

// OptimisticLockError reports errors related to optimistic locking. i.e. when the same record was changed by a different user
// prior to a save completing.
type OptimisticLockError struct {
	message string
	err     error // wrapped error coming from database driver if there is one
}

func (e OptimisticLockError) Error() string {
	return e.message
}

func (e OptimisticLockError) Unwrap() error {
	return e.err
}

func (e OptimisticLockError) Is(err error) bool {
	return e.err == err
}

// NewOptimisticLockError returns a new error related to optimistic locking.
// message should indicate what record was changed prior to a save completing.
// err is the underlying error when the error is generated by the database driver during a rejected transaction, vs.
// detected by the ORM using its own mechanisms.
func NewOptimisticLockError(msg string, err error) error {
	return OptimisticLockError{message: msg, err: err}
}
