//** This file was code generated by GoT. DO NOT EDIT. ***

package template

// This template generates a got template for the db.go file in the orm directory

import (
	"io"

	"github.com/goradd/orm/pkg/codegen"
	"github.com/goradd/orm/pkg/model"
)

func init() {
	t := ConfigTemplate{}
	codegen.RegisterTemplate(&t)
}

// ConfigTemplate generates the db.go file
type ConfigTemplate struct {
	Package string
}

func (tmpl *ConfigTemplate) FileName(dbKey string) string {
	return "config.go"
}

func (tmpl *ConfigTemplate) GenerateDatabase(database *model.Database, _w io.Writer, importPath string) (err error) {
	tmpl.Package = database.Key

	//*** config.tmpl

	if _, err = io.WriteString(_w, `
package `); err != nil {
		return
	}

	if _, err = io.WriteString(_w, tmpl.Package); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `

// Though this file is generated initially, if it exists, it will not be altered.
// Feel free to modify this file to suit your database configuration needs.

import (
	"github.com/goradd/orm/_test/config" // replace with the directory containing your InitDB function for tests.
)


func InitDB() {
	config.InitDB() // replace with your database initialization function
}


`); err != nil {
		return
	}

	return
}

func (tmpl *ConfigTemplate) Overwrite() bool {
	return false
}
