//** This file was code generated by GoT. DO NOT EDIT. ***

package template

import (
	"io"
	"path/filepath"
	"spekary/goradd/orm/pkg/codegen"
	"spekary/goradd/orm/pkg/model"
)

func init() {
	codegen.RegisterTemplate(new(EnumTableNodeTemplate))
}

type EnumTableNodeTemplate struct {
}

func (n *EnumTableNodeTemplate) FileName(table *model.EnumTable) string {
	return filepath.Join(table.DbKey, "orm", "node", table.FileName()+".go")
}

func (n *EnumTableNodeTemplate) GenerateEnum(table *model.EnumTable, _w io.Writer) (err error) {
	return n.gen(table, _w)
}

func (n *EnumTableNodeTemplate) Overwrite() bool {
	return true
}

// enumTableNode

func (n *EnumTableNodeTemplate) gen(table *model.EnumTable, _w io.Writer) (err error) {
	if err = n.genHeader(table, _w); err != nil {
		return
	}
	if err = n.genPrivate(table, _w); err != nil {
		return
	}
	if err = n.genLeafNodes(table, _w); err != nil {
		return
	}
	return
}

func (n *EnumTableNodeTemplate) genHeader(table *model.EnumTable, _w io.Writer) (err error) {

	if _, err = io.WriteString(_w, `// Code generated by goradd. DO NOT EDIT.

package node

import (
    "encoding/gob"
	"github.com/goradd/goradd/pkg/orm/query"
)

type `); err != nil {
		return
	}

	if _, err = io.WriteString(_w, table.Identifier); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `Node struct {
	query.ReferenceNodeI
}

// PrimaryKeyNode returns a node representing the primary key column.
func (n *`); err != nil {
		return
	}

	if _, err = io.WriteString(_w, table.Identifier); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `Node) PrimaryKeyNode() (*query.ColumnNode) {
	return n.`); err != nil {
		return
	}

	if _, err = io.WriteString(_w, table.FieldIdentifier(0)); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `()
}

func init() {
   gob.Register(new(`); err != nil {
		return
	}

	if _, err = io.WriteString(_w, table.Identifier); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `Node))
}

`); err != nil {
		return
	}

	return
}

func (n *EnumTableNodeTemplate) genPrivate(table *model.EnumTable, _w io.Writer) (err error) {

	if _, err = io.WriteString(_w, `// SelectNodes_ is used internally by the framework to return the list of column nodes.
// doc: hide
func (n *`); err != nil {
		return
	}

	if _, err = io.WriteString(_w, table.Identifier); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `Node) SelectNodes_() ([]*query.ColumnNode) {
    return []*query.ColumnNode {
`); err != nil {
		return
	}

	for i := 0; i < len(table.Fields); i++ {

		if _, err = io.WriteString(_w, `	    n.`); err != nil {
			return
		}

		if _, err = io.WriteString(_w, table.FieldIdentifier(i)); err != nil {
			return
		}

		if _, err = io.WriteString(_w, `(),
`); err != nil {
			return
		}

	}

	if _, err = io.WriteString(_w, `	}
}

// EmbeddedNode_ is used internally by the framework to return the embedded ReferenceNodeI.
// doc: hide
func (n *`); err != nil {
		return
	}

	if _, err = io.WriteString(_w, table.Identifier); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `Node) EmbeddedNode_() query.NodeI {
	return n.ReferenceNodeI
}

// Copy_ is used internally by the framework to deep copy the node.
// doc: hide
func (n *`); err != nil {
		return
	}

	if _, err = io.WriteString(_w, table.Identifier); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `Node) Copy_() query.NodeI {
	return &`); err != nil {
		return
	}

	if _, err = io.WriteString(_w, table.Identifier); err != nil {
		return
	}

	if _, err = io.WriteString(_w, `Node{query.CopyNode(n.ReferenceNodeI)}
}

`); err != nil {
		return
	}

	return
}

func (n *EnumTableNodeTemplate) genLeafNodes(table *model.EnumTable, _w io.Writer) (err error) {

	for i := 0; i < len(table.Fields); i++ {
		fn := table.FieldIdentifier(i)

		if _, err = io.WriteString(_w, `
func (n *`); err != nil {
			return
		}

		if _, err = io.WriteString(_w, table.Identifier); err != nil {
			return
		}

		if _, err = io.WriteString(_w, `Node) `); err != nil {
			return
		}

		if _, err = io.WriteString(_w, fn); err != nil {
			return
		}

		if _, err = io.WriteString(_w, `() *query.ColumnNode {

	cn := query.NewColumnNode (
		"`); err != nil {
			return
		}

		if _, err = io.WriteString(_w, table.DbKey); err != nil {
			return
		}

		if _, err = io.WriteString(_w, `",
		"`); err != nil {
			return
		}

		if _, err = io.WriteString(_w, table.QueryName); err != nil {
			return
		}

		if _, err = io.WriteString(_w, `",
		"`); err != nil {
			return
		}

		if _, err = io.WriteString(_w, table.FieldQueryName(i)); err != nil {
			return
		}

		if _, err = io.WriteString(_w, `",
		"`); err != nil {
			return
		}

		if _, err = io.WriteString(_w, fn); err != nil {
			return
		}

		if _, err = io.WriteString(_w, `",
		query.`); err != nil {
			return
		}

		if _, err = io.WriteString(_w, table.FieldReceiverType(i).String()); err != nil {
			return
		}

		if _, err = io.WriteString(_w, `,
		`); err != nil {
			return
		}

		if i == 0 {

			if _, err = io.WriteString(_w, `true`); err != nil {
				return
			}

		} else {

			if _, err = io.WriteString(_w, `false`); err != nil {
				return
			}

		}

		if _, err = io.WriteString(_w, `,
	)
	query.SetParentNode(cn, n)
	return cn
}
`); err != nil {
			return
		}

	}
	return
}
