package query

import (
	"context"
	"testing"
	"time"

	"github.com/goradd/gro/_test/gen/orm/goradd_unit"
	"github.com/stretchr/testify/assert"
)

func TestAutoGeneratedValues(t *testing.T) {
	ctx := context.Background()

	r := goradd_unit.NewAutoGen()
	r.SetName("testAutoGeneratedValues")

	id := r.ID()
	assert.True(t, id.IsTemp())
	assert.True(t, r.GroLock() == 0)
	assert.True(t, r.GroTimestamp() == 0)
	assert.True(t, r.Created().IsZero())
	assert.True(t, r.Modified().IsZero())
	err := r.Save(ctx)
	assert.NoError(t, err)

	id = r.ID()
	assert.False(t, id.IsTemp())

	lock := r.GroLock()
	ts := r.GroTimestamp()
	assert.True(t, lock != 0)
	assert.True(t, ts != 0)
	assert.False(t, r.Created().IsZero())
	assert.False(t, r.Modified().IsZero())
	assert.WithinDuration(t, r.Created(), r.Modified(), time.Millisecond)

	time.Sleep(2 * time.Millisecond)
	r.SetName("testAutoGeneratedValues2")
	err = r.Save(ctx)
	assert.NoError(t, err)

	assert.True(t, r.Created().Add(time.Millisecond).Before(r.Modified()))
	assert.NotEqual(t, lock, r.GroLock())
	assert.NotEqual(t, ts, r.GroTimestamp())
	assert.EqualValues(t, id, r.ID())
}
