package query

import (
	"bytes"
	"database/sql/driver"
	"encoding/gob"
	"encoding/json"
	"sync/atomic"
)

var tempPk = atomic.Int64{}

// AutoPrimaryKey is a custom database type that expresses that the database will be
// generating the primary key for a record. This type can be used as a primary key,
// or as a reference to an AutoPrimaryKey column in another table.
//
// Databases generally either increment a numeric value (most SQL databases),
// generate a pseudo random byte array (MongoDB), or generate a random string.
// Some databases do not have this capability (DynamoDB for one), and database drivers
// for these databases will need to generate a primary key during insert.
//
// This type will store whatever is given it in its native form.
// Therefore, moving to another database with a different primary key generator will require
// some conversions and transformations. If you expect to be changing database engine types,
// consider using a UUID or ULID as a primary key instead.
// String conversion will follow the same rules as json conversion.
type AutoPrimaryKey struct {
	val any
}

// TempAutoPrimaryKey returns an auto primary key that is preset to a temporary unique value
// and is marked to be generated when the record is saved.
// You can use the temporary value as a key to refer to a collection of
// rows that have not yet been saved.
func TempAutoPrimaryKey() AutoPrimaryKey {
	val := temporaryPrimaryKey()
	return AutoPrimaryKey{val: val}
}

func ZeroAutoPrimaryKey() AutoPrimaryKey {
	return AutoPrimaryKey{}
}

// NewAutoPrimaryKey wraps the given value with the AutoPrimaryKey type, specifying that it is
// a generated value.
func NewAutoPrimaryKey(v any) AutoPrimaryKey {
	return AutoPrimaryKey{val: v}
}

func (a AutoPrimaryKey) String() string {
	b, _ := json.Marshal(a.val)
	return string(b)
}

func (a AutoPrimaryKey) Val() any {
	return a.val
}

// IsZero returns true if this is a zero value, which indicates its a reference to
// an AutoPrimaryKey that has not been set.
func (a AutoPrimaryKey) IsZero() bool {
	return a.val == nil
}

// IsTemp returns true if the auto primary key is a temporary value, indicating that it is
// a primary key that is to be generated by the database or driver, but has not yet been
// generated.
func (a AutoPrimaryKey) IsTemp() bool {
	if a.val == nil {
		return false
	}
	if v, ok := a.val.(int64); !ok {
		return false
	} else {
		return v <= 0
	}
}

func (a AutoPrimaryKey) MarshalBinary() ([]byte, error) {
	var b bytes.Buffer

	enc := gob.NewEncoder(&b)
	if err := enc.Encode(a.val == nil); err != nil {
		return nil, err
	}
	if a.val != nil {
		if err := enc.Encode(&a.val); err != nil {
			return nil, err
		}
	}

	return b.Bytes(), nil
}

func (a *AutoPrimaryKey) UnmarshalBinary(b []byte) error {
	var isNil bool

	dec := gob.NewDecoder(bytes.NewReader(b))
	if err := dec.Decode(&isNil); err != nil {
		return err
	}
	if isNil {
		a.val = nil
	} else if err := dec.Decode(&a.val); err != nil {
		return err
	}
	return nil
}

// MarshalJSON exports the underlying value as JSON.
// There is no matching UnmarshalJSON since some database implementations will need to do
// a special conversion from what gets marshalled.
func (a AutoPrimaryKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(a.val)
}

// Value returns the value of the content as a primitive value suitable for use in a SQL
// clause. This satisfies the Valuer interface found in the standard Go SQL driver base,
// making it possible to use an AutoPrimaryKey as an argument in any SQL statement.
func (a AutoPrimaryKey) Value() (driver.Value, error) {
	return a.val, nil
}

// TemporaryPrimaryKey returns an atomically unique negative value to be used as a
// an initial temporary primary key for new records
// that have IDs that are set by the database.
// This makes sure that new records have unique ids that can be used to access
// records.
// The framework will replace this value after the initial insert with whatever the
// database returns.
func temporaryPrimaryKey() int64 {
	i := tempPk.Add(-1)
	return i
}
